version: '3.1'

services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Europe/Paris

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      TZ: Europe/Paris

volumes:
  mariadb_data:
    driver: local
